user-message: "WARNING: This stack project is generated."

# NOTE: We need allow-newer: true because of cabal-testsuite has a
# custom-setup depending on 3.10.* of Cabal and Cabal-syntax while the
# rest of the package depends on 3.11.*.
#
# In the dependencies for cabal-testsuite-3:
#   * Cabal must match ((>=3.10 && <3.11) && >=3.11.0.0 && <3.12) && >=3.10 && <3.11, but Cabal-3.11.0.0 is in the Stack configuration
#     (no matching package and version found. Perhaps there is an error in the specification of a package's dependencies or build-tools
#     (Hpack) or build-depends, build-tools or build-tool-depends (Cabal file) or an omission from the packages list in
#     /.../stack.yaml (project-level configuration).)
#   * Cabal-syntax must match ((>=3.10 && <3.11) && >=3.11.0.0 && <3.12) && >=3.10 && <3.11, but Cabal-syntax-3.11.0.0 is in the Stack
#     configuration (no matching package and version found. Perhaps there is an error in the specification of a package's dependencies
#     or build-tools (Hpack) or build-depends, build-tools or build-tool-depends (Cabal file) or an omission from the packages list in
#     /.../stack.yaml (project-level configuration).)
# needed since cabal-testsuite is a build target.
allow-newer: true

flags:
  rere:
    rere-cfg: false

ghc-options:
  "$locals": -fhide-source-paths


resolver: lts-21.19

# We have 11 packages.
packages:
  - ./Cabal
  - ./Cabal-QuickCheck
  - ./Cabal-described
  - ./Cabal-syntax
  - ./Cabal-tests
  - ./Cabal-tree-diff
  - ./cabal-benchmarks
  - ./cabal-install
  - ./cabal-install-solver
  - ./cabal-testsuite
  - ./solver-benchmarks

# We have 0 source packages listed in this order:
#   * external 0
#   * internal 0
#   * external forks 0
#   * internal forks 0
extra-deps:

  # Source Packages, external (3rd party).

  # Source Packages, internal to this organisation (private and public).

  # Source Packages, external (3rd party) forks of other repositories.
  # Can we help upstream?

  # Source Packages, internal forks of other repositories.
  # Can we upstream and unfork?

  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - directory-1.3.8.1
  - filepath-1.4.100.4
  - process-1.6.17.0
  - rere-0.2
  - semaphore-compat-1.0.0@rev:1
  - unix-2.8.2.1
